actors:
  uribo:
    image_url: /images/actors/uribo.jpg
    name: uribo
    url: https://twitter.com/u_ribo
  yutannihilation:
    image_url: /images/actors/yutannihilation.jpg
    name: yutannihilation
    url: https://twitter.com/yutannihilation
  DAISUKEICHIKAWA:
    image_url: /images/actors/DAISUKEICHIKAWA.jpg
    name: DAISUKEICHIKAWA
    url: https://github.com/DAISUKEICHIKAWA
  IshidaMotohiro:
    image_url: /images/actors/IshidaMotohiro.jpg
    name: IshidaMotohiro
    url: https://github.com/IshidaMotohiro
  _stakaya:
    image_url: /images/actors/stakaya.jpg
    name: _stakaya
    url: https://twitter.com/_stakaya
  kazutan:
    image_url: /images/actors/kazutan.png
    name: kazutan
    url: https://twitter.com/kazutan
  piroyoung:
    image_url: /images/actors/piroyoung.jpg
    name: piroyoung
    url: https://github.com/piroyoung
  MatsuuraKentaro:
    image_url: /images/actors/MatsuuraKentaro.jpg
    name: MatsuuraKentaro
    url: http://statmodeling.hatenablog.com
  y__mattu
    image_url: /images/actors/y__mattu.png
    name: Yuya Matsumura
    url: https://ymattu.github.io/
  koriakane
    image_url: /images/actors/koriakane.png
    name: aca
    url: https://twitter.com/koriakane
  kotatyamtema
    image_url: /images/actors/kotatyamatema.jpg
    name: kotatyamatema
    url: https://twitter.com/kotatyamatema
  kilometer
    image_url: /images/actors/kilometer.jpeg
    name: kilometer
    url: https://twitter.com/kilometer00

author: r3 group
description: RユーザによるRユーザのためのラジオ
description_long: RユーザによるRユーザのためのラジオです。Rについてわいわい話します。
email: suika1127@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
  - logo.pxm
  - r3.Rproj
hashtag: Rラジオ
itunes_podcast_url:
keywords: r,open-source,data-analysis,development,life
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: R Radio for the Rest of us.
url: https://rlangradio.org
